# graphdb is where we will be storing things
# publishing is mostly a source of resource identifiers
# repository is for page id maps

# 'all relationships' id 835 something something

locations:

  # Local testing graphdb supplied from EOL beta instance
  test:
    neo4j: 'http://neo4j:password@localhost:7474'
    publishing: beta_pub
    resources:
    - id: 99999
      name: 'Dummy resource for testing'
      repository_id: 99999

  # Local testing graphdb supplied from EOL production instance
  ptest:
    neo4j: 'http://neo4j:password@localhost:7474'
    publishing: prod_pub

  # EOL beta
  beta:
    via_api: beta_pub
    publishing: beta_pub

  beta_pub:
    # Certificate is not valid for beta.eol.org
    url: 'https://beta.eol.org/'
    token_file: 'beta.token'
    update_token_file: 'beta-admin.token'
    repository: beta_repo

  beta_repo:
    url: 'https://beta-repo.eol.org/'
    resources:
    - id: 723
      name: 'EOL Dynamic Hierarchy 1.1'
      opendataUrl: https://opendata.eol.org/dataset/tram-807-808-809-810-dh-v1-1/resource/00adb47b-57ed-4f6b-8f66-83bfdb5120e8

    - id: 550
      name: '000_English Vernaculars for Landmark Taxa'
      opendataUrl: 'https://opendata.eol.org/dataset/english-vernaculars-for-landmark-taxa/resource/4b1ad94f-0d20-47f1-8a43-c2cb0d670da4'

  # EOL production
  prod:
    via_api: prod_pub
    publishing: prod_pub

  prod_pub:
    url: 'https://eol.org/'
    token_file: '/home/jar/eol/production.token'
    #update_token_file: '/home/jar/eol/production-admin.token'
    repository: prod_repo

  prod_repo:
    url: 'https://content.eol.org/'

  workspace:
    path: '/home/jar/.plotter_workspace'

  staging:
    rsync_command: 'rsync -vaR'
    rsync_specifier: 'varela:public_html/eol/stage'
    url: 'http://varela.csail.mit.edu/~jar/eol/stage'
