# Sample plotter configuration file.  Modify as appropriate for your
# local installation.  See ../README.md

# graphdb is the neo4j graph database, where we will be storing information
# publishing is mostly mainly just a source of resource identifiers
# repository is mostly for page id maps
# dwca is for Darwin Core archives (usually obtained from opendata.eol.org)

locations:

  # Local testing graphdb supplied from EOL production instance
  ptest:
    neo4j: 'http://localhost:7474'
    neo4j_user: 'neo4j'
    neo4j_password: 'set this as appropriate'
    graphdb_name: eol
    publishing: prod_pub

  # EOL beta
  beta:
    via_api: beta_pub
    publishing: beta_pub

  beta_pub:
    # Certificate is not valid for beta.eol.org
    url: 'https://beta.eol.org/'
    token_file: 'beta.token'
    update_token_file: 'beta-admin.token'
    repository: beta_repo

  beta_repo:
    url: 'https://beta-repo.eol.org/'
    resources:
    - id: 723
      name: 'EOL Dynamic Hierarchy 1.1'
      opendataUrl: https://opendata.eol.org/dataset/tram-807-808-809-810-dh-v1-1/resource/00adb47b-57ed-4f6b-8f66-83bfdb5120e8

    - id: 550
      name: '000_English Vernaculars for Landmark Taxa'
      opendataUrl: 'https://opendata.eol.org/dataset/english-vernaculars-for-landmark-taxa/resource/4b1ad94f-0d20-47f1-8a43-c2cb0d670da4'

  # EOL production
  prod:
    via_api: prod_pub
    publishing: prod_pub

  # update_token_file is dangerous - it enables modification of the graphdb.
  # This can totally screw up a deployed system if you're not careful.
  # Un-comment the location if you're ready to trust plotter to do updates.
  prod_pub:
    url: 'https://eol.org/'
    token_file: 'production.token'
    #update_token_file: 'production-admin.token'
    repository: prod_repo

  prod_repo:
    url: 'https://content.eol.org/'

  workspace:
    path: '/home/jar/.plotter_workspace'

  # Replace "stage", "stage.eo.org", and "~user" as appropriate
  staging:
    rsync_command: 'rsync -vaR'
    rsync_specifier: 'stage:public_html/eol/stage'
    url: 'http://stage.eol.org/~user/eol/stage'
