development:
  db:
    name: eol_development
    username: root
    password:
  secret_key_base: ebd78e534a43248430010cf76f951ac7055577dc9dff146e6a74cc858b8128ec102dca4a6bfa03b5db29e5d3f2c9a3bd06c3cbd3ce1b1a8a1f897a0a3c5ffa06
  host:
    name: 'localhost'
    port: 3000
    url: 'http://localhost:3000'
  smtp:
    address: 'localhost'
    port: 1025
  repository:
    url: 'http://localhost:3001'
  image_path:
    original: '' # Yes, nothing.
    ext: '.jpg'
    join: '.'
    by: 'x'
  traitbank_url: 'http://neo4j:neo4j@localhost:7474'
  google_maps_key: 'google_maps_test_key'
  discourse_url: ''
  discourse_user: ''
  discourse_key: ''

test:
  db:
    name: eol_test
    username: root
    password:
  secret_key_base: 099f735bf94ab06af5dfe69e0fbb160a1a051053ecc5e68f983240d9c4b95581ce03ef61a44e18cc766368dde3b0695a1f14da0a6d39e96d827eb1bbe4565776
  google_maps_key: google_maps_test_key
  discourse_url: ""
  discourse_user: ""
  discourse_key: ""
  host:
    name: 'localhost'
    port: 3000
    url: 'http://localhost:3000'
  smtp:
    address: 'localhost'
    port: 1025
  repository:
    url: 'http://localhost:3001'
  image_path:
    original: '' # Yes, nothing.
    ext: '.jpg'
    join: '.'
    by: 'x'
  traitbank_url: 'http://neo4j:neo4j@localhost:7474'
